# Generated by Django 3.1.4 on 2020-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='movie',
            name='netizen_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reporter_critic_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
