# Generated by Django 3.1.4 on 2020-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201211_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(through='movie.MovieActor', to='movie.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(through='movie.MovieGenre', to='movie.Genre'),
        ),
    ]
