# Generated by Django 3.1.4 on 2020-12-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201213_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.genre'),
        ),
    ]
