# Generated by Django 3.1.4 on 2020-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20201213_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='netizen_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reporter_critic_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
